-- ============================================================
-- E-COMMERCE SALES ANALYSIS
-- SQL ANALYSIS QUERIES
-- Tool: MySQL
-- ============================================================


-- ============================================================
-- BASIC SQL ANALYSIS
-- ============================================================

-- Q1. Display all customers
SELECT *
FROM customers;


-- Q2. Find customers from Coimbatore
SELECT *
FROM customers
WHERE city = 'Coimbatore';


-- Q3. Find products with price greater than ₹5,000
SELECT *
FROM products
WHERE price > 5000;


-- Q4. Display products from highest to lowest price
SELECT *
FROM products
ORDER BY price DESC;


-- Q5. Find the total number of customers
SELECT COUNT(*) AS total_customers
FROM customers;


-- Q6. Find the total number of products
SELECT COUNT(*) AS total_products
FROM products;


-- Q7. Find the highest product price
SELECT MAX(price) AS highest_price
FROM products;


-- Q8. Find the lowest product price
SELECT MIN(price) AS lowest_price
FROM products;


-- Q9. Find the average product price
SELECT AVG(price) AS average_price
FROM products;


-- Q10. Find the total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;


-- ============================================================
-- INTERMEDIATE SQL ANALYSIS
-- ============================================================

-- Q11. Find the number of customers in each city
SELECT
    city,
    COUNT(*) AS customer_count
FROM customers
GROUP BY city;


-- Q12. Find the number of products in each category
SELECT
    c.category_name,
    COUNT(p.product_id) AS product_count
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name;


-- Q13. Find the average product price for each category
SELECT
    c.category_name,
    AVG(p.price) AS average_price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name;


-- Q14. Find the highest-priced product in each category
SELECT
    c.category_name,
    MAX(p.price) AS highest_price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name;


-- Q15. Find categories where average product price is greater than ₹3,000
SELECT
    c.category_name,
    AVG(p.price) AS average_price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name
HAVING AVG(p.price) > 3000;


-- Q16. Find total quantity sold for each product
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name;


-- Q17. Find the top 5 products based on total quantity sold
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;


-- Q18. Find the number of orders for each customer
SELECT
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;


-- Q19. Find customers who have placed more than one order
SELECT
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1;


-- Q20. Find total revenue generated from each product
SELECT
    p.product_name,
    SUM(p.price * oi.quantity) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;


-- ============================================================
-- BUSINESS ANALYSIS
-- ============================================================

-- Q21. Display each order with customer name and city
SELECT
    o.order_id,
    c.customer_name,
    c.city,
    o.order_date,
    o.order_status
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id;


-- Q22. Display each order with product name, quantity and price
SELECT
    oi.order_id,
    p.product_name,
    oi.quantity,
    p.price
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id;


-- Q23. Find total revenue from Delivered orders only
SELECT
    SUM(p.price * oi.quantity) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.order_status = 'Delivered';


-- Q24. Find total revenue generated by each customer
SELECT
    c.customer_name,
    SUM(p.price * oi.quantity) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spending DESC;


-- Q25. Find the top 5 customers based on total spending
SELECT
    c.customer_name,
    SUM(p.price * oi.quantity) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spending DESC
LIMIT 5;


-- Q26. Find customers whose total spending is greater than ₹50,000
SELECT
    c.customer_name,
    SUM(p.price * oi.quantity) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.customer_name
HAVING SUM(p.price * oi.quantity) > 50000;


-- Q27. Find the product with the highest total revenue
SELECT
    p.product_name,
    SUM(p.price * oi.quantity) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
LIMIT 1;


-- Q28. Find customers who have never placed an order
SELECT
    c.customer_id,
    c.customer_name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- Q29. Categorize products based on price
SELECT
    product_name,
    price,
    CASE
        WHEN price > 20000 THEN 'Premium'
        WHEN price >= 5000 THEN 'Mid-Range'
        ELSE 'Budget'
    END AS price_category
FROM products;


-- Q30. Find monthly revenue from Delivered orders
SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS sales_month,
    SUM(p.price * oi.quantity) AS monthly_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY sales_month;